# Generated by Django 5.0.3 on 2024-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.FileField(default='media/user_image.jpg', upload_to='media/'),
        ),
    ]
