# Generated by Django 5.0.3 on 2024-03-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.FileField(blank=True, default='media/user_image.jpg', null=True, upload_to='media/'),
        ),
    ]
